global:
  scrape_interval: 15s

scrape_configs:
  - job_name: doorman
    static_configs:
      - targets: ["doorman:80"]

  - job_name: caesar
    static_configs:
      - targets: ["caesar:80"]

  - job_name: herald
    static_configs:
      - targets: ["herald:80"]
