# NATS server — dev (без TLS, внутренняя Docker-сеть)

server_name: nats

jetstream {
  store_dir: "/data"
}

authorization {
  users = [
    {
      user: "doorman"
      password: $NATS_PASSWORD_DOORMAN
      permissions: {
        publish:   ["doorman.>"]
        subscribe: ["herald.otp.requested", "caesar.user.deleted"]
      }
    },
    {
      user: "herald"
      password: $NATS_PASSWORD_HERALD
      permissions: {
        publish:   ["herald.>"]
        subscribe: ["doorman.otp.sent"]
      }
    },
    {
      user: "caesar"
      password: $NATS_PASSWORD_CAESAR
      permissions: {
        publish:   ["caesar.>"]
        subscribe: ["caesar.>", "doorman.user.created"]
      }
    },
    {
      user: "charon"
      password: $NATS_PASSWORD_CHARON
      permissions: {
        publish:   ["charon.>"]
        subscribe: ["charon.>"]
      }
    },
    {
      user: "riddler"
      password: $NATS_PASSWORD_RIDDLER
      permissions: {
        publish:   ["riddler.>"]
        subscribe: ["riddler.>", "sphinx.generation.completed"]
      }
    },
    {
      user: "sphinx"
      password: $NATS_PASSWORD_SPHINX
      permissions: {
        publish:   ["sphinx.generation.completed", "$JS.API.>", "$JS.ACK.>"]
        subscribe: ["riddler.generation.requested", "_INBOX.>"]
      }
    }
  ]
}
